name: dume2
description: DUM-E AI Assistant App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
